[build]
  publish = "."

[[redirects]]
  from = "/sobrenosotros"
  to = "/sobrenosotros.html"
  status = 200

[[redirects]]
  from = "/servicios"
  to = "/servicios.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 200

[[redirects]]
  from = "/faq"
  to = "/faq.html"
  status = 200

[[redirects]]
  from = "/contacto"
  to = "/contacto.html"
  status = 200

[[redirects]]
  from = "/listadepreciosyservicios"
  to = "/listadepreciosyservicios.html"
  status = 200
